# Map that specifies terse descriptive text for use in lists of structure types
# visible to end users who may not know what the structure type values mean.
#
# Contributors: William Kilian, TargetStream Technologies
#
# Copyright 2024 PDF Association, Inc. https://www.pdfa.org

"structure-types":
    Document          : ""
    DocumentFragment  : "2.0"
    Part              : ""
    Art               : "1.x - Article"
    Sect              : "Section"
    Div               : "Division"
    Annot             : "Annotation"
    Artifact          : "2.0"
    Aside             : "2.0"
    BibEntry          : "1.x - Bibliography entry"
    BlockQuote        : "1.x"
    Caption           : ""
    Code              : "1.x"
    Em                : "2.0 - Emphasis"
    FENote            : "2.0 - Footnote/endnote"
    Figure            : ""
    Formula           : ""
    Form              : ""
    H                 : >
        PDF/UA-1 - Heading with level deduced from tag structure
    H1-H6             : "1.x - Headings with specified levels"
    H7+               : "PDF/UA-1 - Headings with specified levels"
    Hn                : "2.0 - Headings with specified levels"
    Index             : "1.x"
    Lbl               : ""
    Link              : ""
    NonStruct         : ""
    Note              : "1.x"
    P                 : ""
    Private           : "1.x"
    Quote             : "1.x"
    Reference         : "1.x"
    Span              : ""
    Strong            : "2.0"
    Sub               : "2.0"
    Title             : "2.0"
    TOC               : "1.x - Table of contents"
    TOCI              : "1.x - Table of contents item"
    L                 : "List"
    LI                : "List item"
    LBody             : "List body"
    Table             : ""
    TR                : "Table row"
    TH                : "Table header cell"
    TD                : "Table data cell"
    THead             : "Table header row group"
    TBody             : "Table body row group"
    TFoot             : "Table footer row group"
    Ruby              : ""
    RB                : "Ruby base text"
    RT                : "Ruby annotation text"
    RP                : "Ruby punctuation"
    Warichu           : ""
    WT                : "Warichu text"
    WP                : "Warichu punctuation"
