# Map that specifies the HTML anchors for WCAG Success Criteria on the WCAG
# specification HTML page.
#
# Anchors and their titles extracted from https://www.w3.org/TR/WCAG22/#toc
# on 2023-11-08.
#
# Contributors: William Kilian, TargetStream Technologies
#
# Copyright 2024 PDF Association, Inc. https://www.pdfa.org

wcag_sc_url: https://www.w3.org/TR/WCAG22/

wcag_sc_anchormap:
    "0.1"    : background-on-wcag-2
    "0.2"    : wcag-2-layers-of-guidance
    "0.3"    : wcag-2-2-supporting-documents
    "0.4"    : requirements-for-wcag-2-2
    "0.5"    : comparison-with-wcag-2-1
    "0.5.1"  : new-features-in-wcag-2-2
    "0.5.2"  : numbering-in-wcag-2-2
    "0.5.3"  : conformance-to-wcag-2-2
    "0.6"    : later-versions-of-accessibility-guidelines
    "1."     : perceivable
    "1.1"    : text-alternatives
    "1.1.1"  : non-text-content
    "1.2"    : time-based-media
    "1.2.1"  : audio-only-and-video-only-prerecorded
    "1.2.2"  : captions-prerecorded
    "1.2.3"  : audio-description-or-media-alternative-prerecorded
    "1.2.4"  : captions-live
    "1.2.5"  : audio-description-prerecorded
    "1.2.6"  : sign-language-prerecorded
    "1.2.7"  : extended-audio-description-prerecorded
    "1.2.8"  : media-alternative-prerecorded
    "1.2.9"  : audio-only-live
    "1.3"    : adaptable
    "1.3.1"  : info-and-relationships
    "1.3.2"  : meaningful-sequence
    "1.3.3"  : sensory-characteristics
    "1.3.4"  : orientation
    "1.3.5"  : identify-input-purpose
    "1.3.6"  : identify-purpose
    "1.4"    : distinguishable
    "1.4.1"  : use-of-color
    "1.4.2"  : audio-control
    "1.4.3"  : contrast-minimum
    "1.4.4"  : resize-text
    "1.4.5"  : images-of-text
    "1.4.6"  : contrast-enhanced
    "1.4.7"  : low-or-no-background-audio
    "1.4.8"  : visual-presentation
    "1.4.9"  : images-of-text-no-exception
    "1.4.10" : reflow
    "1.4.11" : non-text-contrast
    "1.4.12" : text-spacing
    "1.4.13" : content-on-hover-or-focus
    "2."     : operable
    "2.1"    : keyboard-accessible
    "2.1.1"  : keyboard
    "2.1.2"  : no-keyboard-trap
    "2.1.3"  : keyboard-no-exception
    "2.1.4"  : character-key-shortcuts
    "2.2"    : enough-time
    "2.2.1"  : timing-adjustable
    "2.2.2"  : pause-stop-hide
    "2.2.3"  : no-timing
    "2.2.4"  : interruptions
    "2.2.5"  : re-authenticating
    "2.2.6"  : timeouts
    "2.3"    : seizures-and-physical-reactions
    "2.3.1"  : three-flashes-or-below-threshold
    "2.3.2"  : three-flashes
    "2.3.3"  : animation-from-interactions
    "2.4"    : navigable
    "2.4.1"  : bypass-blocks
    "2.4.2"  : page-titled
    "2.4.3"  : focus-order
    "2.4.4"  : link-purpose-in-context
    "2.4.5"  : multiple-ways
    "2.4.6"  : headings-and-labels
    "2.4.7"  : focus-visible
    "2.4.8"  : location
    "2.4.9"  : link-purpose-link-only
    "2.4.10" : section-headings
    "2.4.11" : focus-not-obscured-minimum
    "2.4.12" : focus-not-obscured-enhanced
    "2.4.13" : focus-appearance
    "2.5"    : input-modalities
    "2.5.1"  : pointer-gestures
    "2.5.2"  : pointer-cancellation
    "2.5.3"  : label-in-name
    "2.5.4"  : motion-actuation
    "2.5.5"  : target-size-enhanced
    "2.5.6"  : concurrent-input-mechanisms
    "2.5.7"  : dragging-movements
    "2.5.8"  : target-size-minimum
    "3."     : understandable
    "3.1"    : readable
    "3.1.1"  : language-of-page
    "3.1.2"  : language-of-parts
    "3.1.3"  : unusual-words
    "3.1.4"  : abbreviations
    "3.1.5"  : reading-level
    "3.1.6"  : pronunciation
    "3.2"    : predictable
    "3.2.1"  : on-focus
    "3.2.2"  : on-input
    "3.2.3"  : consistent-navigation
    "3.2.4"  : consistent-identification
    "3.2.5"  : change-on-request
    "3.2.6"  : consistent-help
    "3.3"    : input-assistance
    "3.3.1"  : error-identification
    "3.3.2"  : labels-or-instructions
    "3.3.3"  : error-suggestion
    "3.3.4"  : error-prevention-legal-financial-data
    "3.3.5"  : help
    "3.3.6"  : error-prevention-all
    "3.3.7"  : redundant-entry
    "3.3.8"  : accessible-authentication-minimum
    "3.3.9"  : accessible-authentication-enhanced
    "4."     : robust
    "4.1"    : compatible
    "4.1.1"  : parsing
    "4.1.2"  : name-role-value
    "4.1.3"  : status-messages
    "5."     : conformance
    "5.1"    : interpreting-normative-requirements
    "5.2"    : conformance-reqs
    "5.2.1"  : cc1
    "5.2.2"  : cc2
    "5.2.3"  : cc3
    "5.2.4"  : cc4
    "5.2.5"  : cc5
    "5.3"    : conformance-claims
    "5.3.1"  : conformance-required
    "5.3.2"  : conformance-optional
    "5.4"    : conformance-partial
    "5.5"    : conformance-partial-lang
    "5.6"    : privacy-summary
    "5.7"    : security-summary
    "6."     : glossary
    "7."     : input-purposes
    "A."     : changelog
    "B."     : acknowledgements
    "B.1"    : ack_participants-active
    "B.2"    : ack_participants-previous
    "B.3"    : enabling-funders
    "C."     : references
    "C.1"    : informative-references

wcag_sc_titlemap:
    "0.1"    : Background on WCAG 2
    "0.2"    : WCAG 2 Layers of Guidance
    "0.3"    : WCAG 2.2 Supporting Documents
    "0.4"    : Requirements for WCAG 2.2
    "0.5"    : Comparison with WCAG 2.1
    "0.5.1"  : New Features in WCAG 2.2
    "0.5.2"  : Numbering in WCAG 2.2
    "0.5.3"  : Conformance to WCAG 2.2
    "0.6"    : Later Versions of Accessibility Guidelines
    "1."     : Perceivable
    "1.1"    : Text Alternatives
    "1.1.1"  : Non-text Content
    "1.2"    : Time-based Media
    "1.2.1"  : Audio-only and Video-only (Prerecorded)
    "1.2.2"  : Captions (Prerecorded)
    "1.2.3"  : Audio Description or Media Alternative (Prerecorded)
    "1.2.4"  : Captions (Live)
    "1.2.5"  : Audio Description (Prerecorded)
    "1.2.6"  : Sign Language (Prerecorded)
    "1.2.7"  : Extended Audio Description (Prerecorded)
    "1.2.8"  : Media Alternative (Prerecorded)
    "1.2.9"  : Audio-only (Live)
    "1.3"    : Adaptable
    "1.3.1"  : Info and Relationships
    "1.3.2"  : Meaningful Sequence
    "1.3.3"  : Sensory Characteristics
    "1.3.4"  : Orientation
    "1.3.5"  : Identify Input Purpose
    "1.3.6"  : Identify Purpose
    "1.4"    : Distinguishable
    "1.4.1"  : Use of Color
    "1.4.2"  : Audio Control
    "1.4.3"  : Contrast (Minimum)
    "1.4.4"  : Resize Text
    "1.4.5"  : Images of Text
    "1.4.6"  : Contrast (Enhanced)
    "1.4.7"  : Low or No Background Audio
    "1.4.8"  : Visual Presentation
    "1.4.9"  : Images of Text (No Exception)
    "1.4.10" : Reflow
    "1.4.11" : Non-text Contrast
    "1.4.12" : Text Spacing
    "1.4.13" : Content on Hover or Focus
    "2."     : Operable
    "2.1"    : Keyboard Accessible
    "2.1.1"  : Keyboard
    "2.1.2"  : No Keyboard Trap
    "2.1.3"  : Keyboard (No Exception)
    "2.1.4"  : Character Key Shortcuts
    "2.2"    : Enough Time
    "2.2.1"  : Timing Adjustable
    "2.2.2"  : Pause, Stop, Hide
    "2.2.3"  : No Timing
    "2.2.4"  : Interruptions
    "2.2.5"  : Re-authenticating
    "2.2.6"  : Timeouts
    "2.3"    : Seizures and Physical Reactions
    "2.3.1"  : Three Flashes or Below Threshold
    "2.3.2"  : Three Flashes
    "2.3.3"  : Animation from Interactions
    "2.4"    : Navigable
    "2.4.1"  : Bypass Blocks
    "2.4.2"  : Page Titled
    "2.4.3"  : Focus Order
    "2.4.4"  : Link Purpose (In Context)
    "2.4.5"  : Multiple Ways
    "2.4.6"  : Headings and Labels
    "2.4.7"  : Focus Visible
    "2.4.8"  : Location
    "2.4.9"  : Link Purpose (Link Only)
    "2.4.10" : Section Headings
    "2.4.11" : Focus Not Obscured (Minimum)
    "2.4.12" : Focus Not Obscured (Enhanced)
    "2.4.13" : Focus Appearance
    "2.5"    : Input Modalities
    "2.5.1"  : Pointer Gestures
    "2.5.2"  : Pointer Cancellation
    "2.5.3"  : Label in Name
    "2.5.4"  : Motion Actuation
    "2.5.5"  : Target Size (Enhanced)
    "2.5.6"  : Concurrent Input Mechanisms
    "2.5.7"  : Dragging Movements
    "2.5.8"  : Target Size (Minimum)
    "3."     : Understandable
    "3.1"    : Readable
    "3.1.1"  : Language of Page
    "3.1.2"  : Language of Parts
    "3.1.3"  : Unusual Words
    "3.1.4"  : Abbreviations
    "3.1.5"  : Reading Level
    "3.1.6"  : Pronunciation
    "3.2"    : Predictable
    "3.2.1"  : On Focus
    "3.2.2"  : On Input
    "3.2.3"  : Consistent Navigation
    "3.2.4"  : Consistent Identification
    "3.2.5"  : Change on Request
    "3.2.6"  : Consistent Help
    "3.3"    : Input Assistance
    "3.3.1"  : Error Identification
    "3.3.2"  : Labels or Instructions
    "3.3.3"  : Error Suggestion
    "3.3.4"  : Error Prevention (Legal, Financial, Data)
    "3.3.5"  : Help
    "3.3.6"  : Error Prevention (All)
    "3.3.7"  : Redundant Entry
    "3.3.8"  : Accessible Authentication (Minimum)
    "3.3.9"  : Accessible Authentication (Enhanced)
    "4."     : Robust
    "4.1"    : Compatible
    "4.1.1"  : Parsing (Obsolete and removed)
    "4.1.2"  : Name, Role, Value
    "4.1.3"  : Status Messages
    "5."     : Conformance
    "5.1"    : Interpreting Normative Requirements
    "5.2"    : Conformance Requirements
    "5.2.1"  : Conformance Level
    "5.2.2"  : Full pages
    "5.2.3"  : Complete processes
    "5.2.4"  : Only Accessibility-Supported Ways of Using Technologies
    "5.2.5"  : Non-Interference
    "5.3"    : Conformance Claims (Optional)
    "5.3.1"  : Required Components of a Conformance Claim
    "5.3.2"  : Optional Components of a Conformance Claim
    "5.4"    : Statement of Partial Conformance - Third Party Content
    "5.5"    : Statement of Partial Conformance - Language
    "5.6"    : Privacy Considerations
    "5.7"    : Security Considerations
    "6."     : Glossary
    "7."     : Input Purposes for User Interface Components
    "A."     : Change Log
    "B."     : Acknowledgments
    "B.1"    : >
        Participants of the AG WG active in the development of this document:
    "B.2"    : >
        Other previously active WCAG WG participants and other contributors to
        WCAG 2.0, WCAG 2.1, or supporting resources
    "B.3"    : Enabling funders
    "C."     : References
    "C.1"    : Informative references
